TrajectoryPlannerROS:  
  acc_lim_theta: 3.0
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  escape_reset_dist: 0.1
  escape_reset_theta: 1.57079632679
  escape_vel: -0.1

  heading_lookahead: 1.7
  heading_scoring: false
  heading_scoring_timestep: 0.2

  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  oscillation_reset_dist: 0.05

  occdist_scale: 0.003
  pdist_scale: 1.35
  gdist_scale: 5.0

  restore_defaults: false

  vtheta_samples: 10
  vx_samples: 10
  sim_time: 1.0
  sim_granularity: 0.05
  angular_sim_granularity: 0.25

  dwa: false
  simple_attractor: false
  holonomic_robot: false
  y_vels: -0.3,-0.1,0.1,-0.3

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolernace: true
