map_type: costmap

obstacle_range: 2.5
raytrace_range: 10.0
robot_radius: 0.25

transform_tolerance: 0.2
first_map_only: true
update_min_a: 0.17

static_layer:
    enabled: True

obstacle_layer:
    observation_sources: scan 
    scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 30.0}
    footprint_clearing_enabled: true
    track_unknown_space: true

inflation_layer:
    enabled: True
    inflation_radius: 0.5
    cost_scaling_factor: 5.0
