DWAPlannerROS:
  #max_vel_x: 0.45
  #min_vel_x: -0.45
  #max_vel_theta: 1.0
  #min_in_place_vel_theta: 0.4

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  acc_limit_trans: 2.5

  max_trans_vel: 0.45
  min_trans_vel: 0.0

  max_vel_x: 0.45
  min_vel_x: 0.0 #disable backward motion, unstable

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_rot_vel: 3.0 # == (0.45 * 2 ) / 0.3
  min_rot_vel: 0.1 #?

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  sim_time: 2.0
  sim_granularity: 0.05

  vx_samples: 20
  vy_samples: 1
  vth_samples: 20

  prune_plan: true
  holonomic_robot: false

  goal_distance_bias: 0.6
  path_distance_bias: 0.8
  occdist_scale: 0.01
