global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 1.0
   width: 40.0
   height: 40.0
   resolution: 0.05
   static_map: true
   rolling_window: false

   plugins:
       - {name: static_layer, type: "costmap_2d::StaticLayer"}
       - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
       - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
