map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.2,0.2],[0.2,-0.2],[-0.2,-0.2],[-0.2,0.2]]

transform_tolerance: 0.2
first_map_only: true
update_min_a: 0.17

static_layer:
    enabled: True

obstacle_layer:
    observation_sources: scan 
    scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 40.0}

inflation_layer:
    enabled: True
    inflation_radius: 0.3
