map_type: costmap

obstacle_range: 30.0
raytrace_range: 10.0

transform_tolerance: 0.1

static_layer:
    enabled: True

obstacle_layer:
    observation_sources: scan 
    scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

inflation_layer:
    enabled: True
    inflation_radius: 0.3
