recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

conservative_reset:
    reset_distance: 3.0
    layer_names: ["obstacle_layer"]

aggressive_reset:
    reset_distance: 0.0
    layer_names: ["obstacle_layer"]
