TEBLocalPlannerROS:
  acc_lim_x: 2.5
  acc_lim_theta: 3.0

  max_vel_x: 0.4
  max_vel_x_backwards: 0.1

  max_vel_theta: 1.0
  min_turning_radius: 0.0
  wheelbase: 0.0

  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0 #?
